services:
  # MongoDB for both auth and event services
  mongodb:
    image: mongo:7.0
    container_name: birdie-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - birdie-network

  # RabbitMQ for event service message queue
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: birdie-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - birdie-network


  # Gateway API
  gateway:
    build: ./gateway
    container_name: birdie-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - EVENT_SERVICE_URL=http://event-service:3003
      - REGISTRATION_SERVICE_URL=http://registration-service:3005
    depends_on:
      - auth-service
      - event-service
      - registration-service
    networks:
      - birdie-network

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: birdie-auth-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - USER_DB_URI=mongodb+srv://birdie_admin:AppUser%232025%21@birdie-bash-cluster.lwadyko.mongodb.net/user?retryWrites=true&w=majority&appName=birdie-bash-cluster
    depends_on:
      - mongodb
    networks:
      - birdie-network

  # Event Service
  event-service:
    build: ./event-service
    container_name: birdie-event-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - EVENT_DB_URI=mongodb+srv://birdie_admin:AppUser%232025%21@birdie-bash-cluster.lwadyko.mongodb.net/event?retryWrites=true&w=majority&appName=birdie-bash-cluster
      - RABBIT_URL=amqp://admin:password123@rabbitmq:5672
      - RABBIT_EXCHANGE=events
      - ENABLE_CAPACITY_WORKER=true
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - birdie-network

  # Registration Service
  registration-service:
    build: ./registration-service
    container_name: birdie-registration-service
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - REG_DB_URI=mongodb+srv://birdie_admin:AppUser%232025%21@birdie-bash-cluster.lwadyko.mongodb.net/registration?retryWrites=true&w=majority&appName=birdie-bash-cluster
      - EVENT_SERVICE_URL=http://event-service:3003
      - RABBIT_URL=amqp://admin:password123@rabbitmq:5672
      - RABBIT_EXCHANGE=events
      - ENABLE_WAITLIST_WORKER=true
    depends_on:
      - rabbitmq
      - event-service
    networks:
      - birdie-network


volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  birdie-network:
    driver: bridge