// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hszttrnfdzyftwoqfhgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzenR0cm5mZHp5ZnR3b3FmaGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDMyOTQsImV4cCI6MjA2NTkxOTI5NH0.36YEuNiGoxCi83AGd4MRx1MnQtDvt-85hZEy_HD66h4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);